// <auto-generated />
namespace IAS_Handyman.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LazyLoadingEnabled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LazyLoadingEnabled));
        
        string IMigrationMetadata.Id
        {
            get { return "202102232250080_LazyLoadingEnabled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
